[2025-04-14 15:56:44 +0100] [5679] [INFO] Starting gunicorn 23.0.0
[2025-04-14 15:56:44 +0100] [5679] [INFO] Listening at: http://127.0.0.1:7890 (5679)
[2025-04-14 15:56:44 +0100] [5679] [INFO] Using worker: sync
[2025-04-14 15:56:44 +0100] [5680] [INFO] Booting worker with pid: 5680
[2025-04-14 15:56:44 +0100] [5681] [INFO] Booting worker with pid: 5681
[2025-04-14 15:56:44 +0100] [5682] [INFO] Booting worker with pid: 5682
[2025-04-14 15:56:44 +0100] [5683] [INFO] Booting worker with pid: 5683
[2025-04-14 16:07:24 +0100] [5679] [INFO] Handling signal: int
[2025-04-14 16:07:24 +0100] [5681] [INFO] Worker exiting (pid: 5681)
[2025-04-14 16:07:24 +0100] [5683] [INFO] Worker exiting (pid: 5683)
[2025-04-14 16:07:24 +0100] [5680] [INFO] Worker exiting (pid: 5680)
[2025-04-14 16:07:24 +0100] [5682] [INFO] Worker exiting (pid: 5682)
[2025-04-14 16:07:25 +0100] [5679] [INFO] Shutting down: Master
[2025-04-14 16:08:10 +0100] [5890] [INFO] Starting gunicorn 23.0.0
[2025-04-14 16:08:10 +0100] [5890] [INFO] Listening at: http://127.0.0.1:7890 (5890)
[2025-04-14 16:08:10 +0100] [5890] [INFO] Using worker: sync
[2025-04-14 16:08:10 +0100] [5891] [INFO] Booting worker with pid: 5891
[2025-04-14 16:08:10 +0100] [5892] [INFO] Booting worker with pid: 5892
[2025-04-14 16:08:10 +0100] [5893] [INFO] Booting worker with pid: 5893
[2025-04-14 16:08:10 +0100] [5894] [INFO] Booting worker with pid: 5894
[2025-04-14 16:14:01 +0100] [5890] [INFO] Handling signal: int
[2025-04-14 16:14:01 +0100] [5892] [INFO] Worker exiting (pid: 5892)
[2025-04-14 16:14:01 +0100] [5891] [INFO] Worker exiting (pid: 5891)
[2025-04-14 16:14:01 +0100] [5894] [INFO] Worker exiting (pid: 5894)
[2025-04-14 16:14:01 +0100] [5893] [INFO] Worker exiting (pid: 5893)
[2025-04-14 16:14:01 +0100] [5890] [INFO] Shutting down: Master
[2025-04-14 16:15:16 +0100] [6034] [INFO] Starting gunicorn 23.0.0
[2025-04-14 16:15:16 +0100] [6034] [INFO] Listening at: http://127.0.0.1:7890 (6034)
[2025-04-14 16:15:16 +0100] [6034] [INFO] Using worker: sync
[2025-04-14 16:15:16 +0100] [6035] [INFO] Booting worker with pid: 6035
[2025-04-14 16:15:16 +0100] [6036] [INFO] Booting worker with pid: 6036
[2025-04-14 16:15:16 +0100] [6037] [INFO] Booting worker with pid: 6037
[2025-04-14 16:15:16 +0100] [6038] [INFO] Booting worker with pid: 6038
[2025-04-14 16:17:45 +0100] [6034] [CRITICAL] WORKER TIMEOUT (pid:6038)
[2025-04-14 16:17:45 +0100] [6038] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-14 16:17:45 +0100] [6038] [INFO] Worker exiting (pid: 6038)
[2025-04-14 16:17:46 +0100] [6095] [INFO] Booting worker with pid: 6095
[2025-04-14 16:18:16 +0100] [6034] [CRITICAL] WORKER TIMEOUT (pid:6036)
[2025-04-14 16:18:16 +0100] [6036] [INFO] Worker exiting (pid: 6036)
[2025-04-14 16:18:16 +0100] [6034] [ERROR] Worker (pid:6036) exited with code 1
[2025-04-14 16:18:16 +0100] [6034] [ERROR] Worker (pid:6036) exited with code 1.
[2025-04-14 16:18:16 +0100] [6109] [INFO] Booting worker with pid: 6109
[2025-04-14 16:26:51 +0100] [6034] [INFO] Handling signal: int
[2025-04-14 16:26:51 +0100] [6095] [INFO] Worker exiting (pid: 6095)
[2025-04-14 16:26:51 +0100] [6035] [INFO] Worker exiting (pid: 6035)
[2025-04-14 16:26:51 +0100] [6037] [INFO] Worker exiting (pid: 6037)
[2025-04-14 16:26:51 +0100] [6109] [INFO] Worker exiting (pid: 6109)
[2025-04-14 16:26:52 +0100] [6034] [INFO] Shutting down: Master
[2025-04-14 16:32:57 +0100] [6351] [INFO] Starting gunicorn 23.0.0
[2025-04-14 16:32:57 +0100] [6351] [INFO] Listening at: http://127.0.0.1:7890 (6351)
[2025-04-14 16:32:57 +0100] [6351] [INFO] Using worker: sync
[2025-04-14 16:32:57 +0100] [6352] [INFO] Booting worker with pid: 6352
[2025-04-14 16:32:57 +0100] [6353] [INFO] Booting worker with pid: 6353
[2025-04-14 16:32:57 +0100] [6354] [INFO] Booting worker with pid: 6354
[2025-04-14 16:32:57 +0100] [6355] [INFO] Booting worker with pid: 6355
[2025-04-14 16:33:48 +0100] [6351] [INFO] Handling signal: int
[2025-04-14 16:33:48 +0100] [6354] [INFO] Worker exiting (pid: 6354)
[2025-04-14 16:33:48 +0100] [6355] [INFO] Worker exiting (pid: 6355)
[2025-04-14 16:33:48 +0100] [6353] [INFO] Worker exiting (pid: 6353)
[2025-04-14 16:33:48 +0100] [6352] [INFO] Worker exiting (pid: 6352)
[2025-04-14 16:33:48 +0100] [6351] [INFO] Shutting down: Master
[2025-04-14 16:34:17 +0100] [6387] [INFO] Starting gunicorn 23.0.0
[2025-04-14 16:34:17 +0100] [6387] [INFO] Listening at: http://127.0.0.1:7890 (6387)
[2025-04-14 16:34:17 +0100] [6387] [INFO] Using worker: sync
[2025-04-14 16:34:17 +0100] [6388] [INFO] Booting worker with pid: 6388
[2025-04-14 16:34:17 +0100] [6389] [INFO] Booting worker with pid: 6389
[2025-04-14 16:34:17 +0100] [6390] [INFO] Booting worker with pid: 6390
[2025-04-14 16:34:17 +0100] [6391] [INFO] Booting worker with pid: 6391
[2025-04-14 16:38:28 +0100] [6387] [INFO] Handling signal: int
[2025-04-14 16:38:28 +0100] [6389] [INFO] Worker exiting (pid: 6389)
[2025-04-14 16:38:28 +0100] [6388] [INFO] Worker exiting (pid: 6388)
[2025-04-14 16:38:28 +0100] [6391] [INFO] Worker exiting (pid: 6391)
[2025-04-14 16:38:28 +0100] [6390] [INFO] Worker exiting (pid: 6390)
[2025-04-14 16:38:28 +0100] [6387] [INFO] Shutting down: Master
[2025-04-14 16:40:37 +0100] [6501] [INFO] Starting gunicorn 23.0.0
[2025-04-14 16:40:37 +0100] [6501] [INFO] Listening at: http://127.0.0.1:7890 (6501)
[2025-04-14 16:40:37 +0100] [6501] [INFO] Using worker: sync
[2025-04-14 16:40:37 +0100] [6502] [INFO] Booting worker with pid: 6502
[2025-04-14 16:40:37 +0100] [6504] [INFO] Booting worker with pid: 6504
[2025-04-14 16:40:38 +0100] [6505] [INFO] Booting worker with pid: 6505
[2025-04-14 16:40:38 +0100] [6507] [INFO] Booting worker with pid: 6507
[2025-04-14 16:43:26 +0100] [6501] [INFO] Handling signal: int
[2025-04-14 16:43:26 +0100] [6504] [INFO] Worker exiting (pid: 6504)
[2025-04-14 16:43:26 +0100] [6502] [INFO] Worker exiting (pid: 6502)
[2025-04-14 16:43:26 +0100] [6505] [INFO] Worker exiting (pid: 6505)
[2025-04-14 16:43:26 +0100] [6507] [INFO] Worker exiting (pid: 6507)
[2025-04-14 16:43:26 +0100] [6501] [INFO] Shutting down: Master
[2025-04-14 16:46:24 +0100] [6641] [INFO] Starting gunicorn 23.0.0
[2025-04-14 16:46:24 +0100] [6641] [INFO] Listening at: http://127.0.0.1:7890 (6641)
[2025-04-14 16:46:24 +0100] [6641] [INFO] Using worker: sync
[2025-04-14 16:46:24 +0100] [6642] [INFO] Booting worker with pid: 6642
[2025-04-14 16:46:24 +0100] [6643] [INFO] Booting worker with pid: 6643
[2025-04-14 16:46:24 +0100] [6644] [INFO] Booting worker with pid: 6644
[2025-04-14 16:46:24 +0100] [6645] [INFO] Booting worker with pid: 6645
[2025-04-14 16:47:34 +0100] [6679] [INFO] Starting gunicorn 23.0.0
[2025-04-14 16:47:34 +0100] [6679] [INFO] Listening at: http://192.168.253.133:7890 (6679)
[2025-04-14 16:47:34 +0100] [6679] [INFO] Using worker: sync
[2025-04-14 16:47:34 +0100] [6680] [INFO] Booting worker with pid: 6680
[2025-04-14 16:47:34 +0100] [6681] [INFO] Booting worker with pid: 6681
[2025-04-14 16:47:34 +0100] [6682] [INFO] Booting worker with pid: 6682
[2025-04-14 16:47:34 +0100] [6683] [INFO] Booting worker with pid: 6683
[2025-04-14 16:49:02 +0100] [6679] [CRITICAL] WORKER TIMEOUT (pid:6681)
[2025-04-14 16:49:02 +0100] [6679] [CRITICAL] WORKER TIMEOUT (pid:6683)
[2025-04-14 16:49:02 +0100] [6683] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-14 16:49:02 +0100] [6681] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-14 16:49:02 +0100] [6681] [INFO] Worker exiting (pid: 6681)
[2025-04-14 16:49:02 +0100] [6683] [INFO] Worker exiting (pid: 6683)
[2025-04-14 16:49:03 +0100] [6704] [INFO] Booting worker with pid: 6704
[2025-04-14 16:49:03 +0100] [6705] [INFO] Booting worker with pid: 6705
[2025-04-14 23:45:08 +0100] [6641] [CRITICAL] WORKER TIMEOUT (pid:6642)
[2025-04-14 23:45:08 +0100] [6642] [INFO] Worker exiting (pid: 6642)
[2025-04-14 23:45:09 +0100] [6641] [ERROR] Worker (pid:6642) exited with code 1
[2025-04-14 23:45:09 +0100] [6641] [ERROR] Worker (pid:6642) exited with code 1.
[2025-04-14 23:45:09 +0100] [9754] [INFO] Booting worker with pid: 9754
[2025-04-15 08:07:59 +0100] [6679] [INFO] Handling signal: winch
[2025-04-15 08:07:59 +0100] [6641] [INFO] Handling signal: winch
[2025-04-15 12:32:06 +0100] [6641] [INFO] Handling signal: winch
[2025-04-15 12:32:06 +0100] [6679] [INFO] Handling signal: winch
[2025-04-15 14:18:32 +0100] [6641] [INFO] Handling signal: int
[2025-04-15 14:18:32 +0100] [6679] [INFO] Handling signal: int
[2025-04-15 14:18:32 +0100] [9754] [INFO] Worker exiting (pid: 9754)
[2025-04-15 14:18:32 +0100] [6644] [INFO] Worker exiting (pid: 6644)
[2025-04-15 14:18:32 +0100] [6645] [INFO] Worker exiting (pid: 6645)
[2025-04-15 14:18:32 +0100] [6704] [INFO] Worker exiting (pid: 6704)
[2025-04-15 14:18:32 +0100] [6682] [INFO] Worker exiting (pid: 6682)
[2025-04-15 14:18:32 +0100] [6705] [INFO] Worker exiting (pid: 6705)
[2025-04-15 14:18:32 +0100] [6680] [INFO] Worker exiting (pid: 6680)
[2025-04-15 14:18:32 +0100] [6643] [INFO] Worker exiting (pid: 6643)
[2025-04-15 14:18:33 +0100] [6679] [INFO] Shutting down: Master
[2025-04-15 14:18:33 +0100] [6641] [INFO] Shutting down: Master
[2025-04-15 14:19:03 +0100] [12043] [INFO] Starting gunicorn 23.0.0
[2025-04-15 14:19:03 +0100] [12043] [INFO] Listening at: http://192.168.253.133:7890 (12043)
[2025-04-15 14:19:03 +0100] [12043] [INFO] Using worker: sync
[2025-04-15 14:19:03 +0100] [12044] [INFO] Booting worker with pid: 12044
[2025-04-15 14:19:03 +0100] [12045] [INFO] Booting worker with pid: 12045
[2025-04-15 14:19:03 +0100] [12046] [INFO] Booting worker with pid: 12046
[2025-04-15 14:19:03 +0100] [12047] [INFO] Booting worker with pid: 12047
[2025-04-15 14:48:16 +0100] [12043] [CRITICAL] WORKER TIMEOUT (pid:12046)
[2025-04-15 14:48:16 +0100] [12046] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-15 14:48:16 +0100] [12046] [INFO] Worker exiting (pid: 12046)
[2025-04-15 14:48:16 +0100] [12593] [INFO] Booting worker with pid: 12593
[2025-04-15 14:57:18 +0100] [12043] [CRITICAL] WORKER TIMEOUT (pid:12044)
[2025-04-15 14:57:18 +0100] [12044] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-15 14:57:18 +0100] [12044] [INFO] Worker exiting (pid: 12044)
[2025-04-15 14:57:18 +0100] [12745] [INFO] Booting worker with pid: 12745
[2025-04-15 14:57:18 +0100] [12745] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/server.py", line 136
    n)
     ^
SyntaxError: unmatched ')'
[2025-04-15 14:57:18 +0100] [12745] [INFO] Worker exiting (pid: 12745)
[2025-04-15 14:57:18 +0100] [12043] [ERROR] Worker (pid:12745) exited with code 3
[2025-04-15 14:57:18 +0100] [12045] [INFO] Worker exiting (pid: 12045)
[2025-04-15 14:57:30 +0100] [12593] [INFO] Worker exiting (pid: 12593)
[2025-04-15 14:57:30 +0100] [12047] [INFO] Worker exiting (pid: 12047)
[2025-04-15 14:57:30 +0100] [12043] [ERROR] Shutting down: Master
[2025-04-15 14:57:30 +0100] [12043] [ERROR] Reason: Worker failed to boot.
[2025-04-15 15:06:23 +0100] [12928] [INFO] Starting gunicorn 23.0.0
[2025-04-15 15:06:23 +0100] [12928] [INFO] Listening at: http://192.168.253.133:7890 (12928)
[2025-04-15 15:06:23 +0100] [12928] [INFO] Using worker: sync
[2025-04-15 15:06:23 +0100] [12929] [INFO] Booting worker with pid: 12929
[2025-04-15 15:06:23 +0100] [12930] [INFO] Booting worker with pid: 12930
[2025-04-15 15:06:24 +0100] [12931] [INFO] Booting worker with pid: 12931
[2025-04-15 15:06:24 +0100] [12932] [INFO] Booting worker with pid: 12932
[2025-04-15 15:14:18 +0100] [12928] [CRITICAL] WORKER TIMEOUT (pid:12930)
[2025-04-15 15:14:18 +0100] [12928] [CRITICAL] WORKER TIMEOUT (pid:12932)
[2025-04-15 15:14:18 +0100] [12932] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-15 15:14:18 +0100] [12930] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-15 15:14:18 +0100] [12930] [INFO] Worker exiting (pid: 12930)
[2025-04-15 15:14:18 +0100] [12932] [INFO] Worker exiting (pid: 12932)
[2025-04-15 15:14:18 +0100] [13072] [INFO] Booting worker with pid: 13072
[2025-04-15 15:14:18 +0100] [13073] [INFO] Booting worker with pid: 13073
[2025-04-15 15:27:54 +0100] [12928] [INFO] Handling signal: int
[2025-04-15 15:27:55 +0100] [13072] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-15 15:27:55 +0100] [12929] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-15 15:27:55 +0100] [13073] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-15 15:27:55 +0100] [12929] [INFO] Worker exiting (pid: 12929)
[2025-04-15 15:27:55 +0100] [12931] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-15 15:27:55 +0100] [13073] [INFO] Worker exiting (pid: 13073)
[2025-04-15 15:27:55 +0100] [12931] [INFO] Worker exiting (pid: 12931)
[2025-04-15 15:27:55 +0100] [13072] [INFO] Worker exiting (pid: 13072)
[2025-04-15 15:27:55 +0100] [12928] [INFO] Shutting down: Master
[2025-04-15 15:28:37 +0100] [13396] [INFO] Starting gunicorn 23.0.0
[2025-04-15 15:28:37 +0100] [13396] [INFO] Listening at: http://192.168.253.133:7890 (13396)
[2025-04-15 15:28:37 +0100] [13396] [INFO] Using worker: sync
[2025-04-15 15:28:37 +0100] [13397] [INFO] Booting worker with pid: 13397
[2025-04-15 15:28:37 +0100] [13398] [INFO] Booting worker with pid: 13398
[2025-04-15 15:28:37 +0100] [13399] [INFO] Booting worker with pid: 13399
[2025-04-15 15:28:37 +0100] [13400] [INFO] Booting worker with pid: 13400
[2025-04-15 15:32:46 +0100] [13396] [INFO] Handling signal: int
[2025-04-15 15:32:46 +0100] [13397] [INFO] Worker exiting (pid: 13397)
[2025-04-15 15:32:46 +0100] [13400] [INFO] Worker exiting (pid: 13400)
[2025-04-15 15:32:46 +0100] [13398] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-15 15:32:46 +0100] [13399] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-15 15:32:47 +0100] [13398] [INFO] Worker exiting (pid: 13398)
[2025-04-15 15:32:47 +0100] [13399] [INFO] Worker exiting (pid: 13399)
[2025-04-15 15:32:47 +0100] [13396] [INFO] Shutting down: Master
[2025-04-15 15:33:15 +0100] [13519] [INFO] Starting gunicorn 23.0.0
[2025-04-15 15:33:15 +0100] [13519] [INFO] Listening at: http://192.168.253.133:7890 (13519)
[2025-04-15 15:33:15 +0100] [13519] [INFO] Using worker: sync
[2025-04-15 15:33:15 +0100] [13520] [INFO] Booting worker with pid: 13520
[2025-04-15 15:33:15 +0100] [13521] [INFO] Booting worker with pid: 13521
[2025-04-15 15:33:15 +0100] [13522] [INFO] Booting worker with pid: 13522
[2025-04-15 15:33:15 +0100] [13523] [INFO] Booting worker with pid: 13523
[2025-04-15 15:44:13 +0100] [13755] [INFO] Starting gunicorn 23.0.0
[2025-04-15 15:44:13 +0100] [13755] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-15 15:44:13 +0100] [13755] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-15 15:44:14 +0100] [13755] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-15 15:44:14 +0100] [13755] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-15 15:44:15 +0100] [13755] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-15 15:44:15 +0100] [13755] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-15 15:44:16 +0100] [13755] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-15 15:44:16 +0100] [13755] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-15 15:44:17 +0100] [13755] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-15 15:44:17 +0100] [13755] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-15 15:44:18 +0100] [13755] [ERROR] Can't connect to ('192.168.253.133', 7890)
[2025-04-15 17:01:16 +0100] [13523] [WARNING] Invalid request from ip=192.168.253.147: Invalid HTTP method: '\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03ë%Ç\x02»\x87\x86¹¾\x12~y\x8fÍE\x8f\x19\x0cKËT\x9c>Ò\x10i\x8eü|\x85\x00Ê'
[2025-04-15 17:04:11 +0100] [13519] [CRITICAL] WORKER TIMEOUT (pid:13520)
[2025-04-15 17:04:11 +0100] [13520] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-15 17:04:11 +0100] [13520] [INFO] Worker exiting (pid: 13520)
[2025-04-15 17:04:11 +0100] [17039] [INFO] Booting worker with pid: 17039
[2025-04-15 17:34:08 +0100] [13519] [CRITICAL] WORKER TIMEOUT (pid:17039)
[2025-04-15 17:34:08 +0100] [17039] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-15 17:34:08 +0100] [17039] [INFO] Worker exiting (pid: 17039)
[2025-04-15 17:34:08 +0100] [17685] [INFO] Booting worker with pid: 17685
[2025-04-15 19:08:27 +0100] [13519] [CRITICAL] WORKER TIMEOUT (pid:13523)
[2025-04-15 19:08:27 +0100] [13523] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-15 19:08:27 +0100] [13523] [INFO] Worker exiting (pid: 13523)
[2025-04-15 19:08:27 +0100] [17991] [INFO] Booting worker with pid: 17991
[2025-04-15 23:30:38 +0100] [17991] [INFO] Worker exiting (pid: 17991)
[2025-04-15 23:30:38 +0100] [22116] [INFO] Booting worker with pid: 22116
[2025-04-15 23:30:46 +0100] [17685] [INFO] Worker exiting (pid: 17685)
[2025-04-15 23:30:47 +0100] [22119] [INFO] Booting worker with pid: 22119
[2025-04-15 23:31:07 +0100] [13521] [INFO] Worker exiting (pid: 13521)
[2025-04-15 23:31:07 +0100] [22125] [INFO] Booting worker with pid: 22125
[2025-04-15 23:31:10 +0100] [13522] [INFO] Worker exiting (pid: 13522)
[2025-04-15 23:31:11 +0100] [22128] [INFO] Booting worker with pid: 22128
[2025-04-15 23:31:41 +0100] [22116] [INFO] Worker exiting (pid: 22116)
[2025-04-15 23:31:41 +0100] [22146] [INFO] Booting worker with pid: 22146
[2025-04-15 23:31:44 +0100] [22119] [INFO] Worker exiting (pid: 22119)
[2025-04-15 23:31:44 +0100] [22149] [INFO] Booting worker with pid: 22149
[2025-04-15 23:31:49 +0100] [22125] [INFO] Worker exiting (pid: 22125)
[2025-04-15 23:31:49 +0100] [22152] [INFO] Booting worker with pid: 22152
[2025-04-15 23:31:52 +0100] [22128] [INFO] Worker exiting (pid: 22128)
[2025-04-15 23:31:52 +0100] [22154] [INFO] Booting worker with pid: 22154
[2025-04-15 23:33:09 +0100] [22146] [INFO] Worker exiting (pid: 22146)
[2025-04-15 23:33:09 +0100] [22181] [INFO] Booting worker with pid: 22181
[2025-04-15 23:33:12 +0100] [22149] [INFO] Worker exiting (pid: 22149)
[2025-04-15 23:33:12 +0100] [22184] [INFO] Booting worker with pid: 22184
[2025-04-15 23:33:18 +0100] [22152] [INFO] Worker exiting (pid: 22152)
[2025-04-15 23:33:19 +0100] [22187] [INFO] Booting worker with pid: 22187
[2025-04-15 23:33:21 +0100] [22154] [INFO] Worker exiting (pid: 22154)
[2025-04-15 23:33:21 +0100] [22190] [INFO] Booting worker with pid: 22190
[2025-04-15 23:53:22 +0100] [22653] [INFO] Starting gunicorn 23.0.0
[2025-04-15 23:53:22 +0100] [22653] [INFO] Listening at: http://192.168.54.204:7890 (22653)
[2025-04-15 23:53:22 +0100] [22653] [INFO] Using worker: sync
[2025-04-15 23:53:22 +0100] [22654] [INFO] Booting worker with pid: 22654
[2025-04-15 23:53:22 +0100] [22655] [INFO] Booting worker with pid: 22655
[2025-04-15 23:53:22 +0100] [22656] [INFO] Booting worker with pid: 22656
[2025-04-15 23:53:22 +0100] [22657] [INFO] Booting worker with pid: 22657
[2025-04-16 00:00:39 +0100] [22833] [INFO] Starting gunicorn 23.0.0
[2025-04-16 00:00:39 +0100] [22833] [INFO] Listening at: http://192.168.54.204:7890 (22833)
[2025-04-16 00:00:39 +0100] [22833] [INFO] Using worker: sync
[2025-04-16 00:00:39 +0100] [22834] [INFO] Booting worker with pid: 22834
[2025-04-16 00:00:39 +0100] [22835] [INFO] Booting worker with pid: 22835
[2025-04-16 00:00:39 +0100] [22836] [INFO] Booting worker with pid: 22836
[2025-04-16 00:00:39 +0100] [22837] [INFO] Booting worker with pid: 22837
[2025-04-16 00:04:48 +0100] [22924] [INFO] Starting gunicorn 23.0.0
[2025-04-16 00:04:48 +0100] [22924] [INFO] Listening at: http://192.168.54.204:7890 (22924)
[2025-04-16 00:04:48 +0100] [22924] [INFO] Using worker: sync
[2025-04-16 00:04:48 +0100] [22925] [INFO] Booting worker with pid: 22925
[2025-04-16 00:04:49 +0100] [22926] [INFO] Booting worker with pid: 22926
[2025-04-16 00:04:49 +0100] [22927] [INFO] Booting worker with pid: 22927
[2025-04-16 00:04:49 +0100] [22928] [INFO] Booting worker with pid: 22928
[2025-04-16 00:07:11 +0100] [22924] [CRITICAL] WORKER TIMEOUT (pid:22928)
[2025-04-16 00:07:11 +0100] [22928] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-16 00:07:11 +0100] [22928] [INFO] Worker exiting (pid: 22928)
[2025-04-16 00:07:11 +0100] [22963] [INFO] Booting worker with pid: 22963
[2025-04-16 00:17:59 +0100] [22924] [CRITICAL] WORKER TIMEOUT (pid:22927)
[2025-04-16 00:17:59 +0100] [22927] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-16 00:17:59 +0100] [22927] [INFO] Worker exiting (pid: 22927)
[2025-04-16 00:17:59 +0100] [23203] [INFO] Booting worker with pid: 23203
[2025-04-16 00:25:51 +0100] [22924] [CRITICAL] WORKER TIMEOUT (pid:23203)
[2025-04-16 00:25:51 +0100] [23203] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-16 00:25:51 +0100] [23203] [INFO] Worker exiting (pid: 23203)
[2025-04-16 00:25:51 +0100] [23324] [INFO] Booting worker with pid: 23324
[2025-04-16 00:44:05 +0100] [22924] [CRITICAL] WORKER TIMEOUT (pid:22925)
[2025-04-16 00:44:05 +0100] [22925] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-16 00:44:05 +0100] [22925] [INFO] Worker exiting (pid: 22925)
[2025-04-16 00:44:05 +0100] [22924] [ERROR] Worker (pid:22925) exited with code 120
[2025-04-16 00:44:05 +0100] [22924] [ERROR] Worker (pid:22925) exited with code 120.
[2025-04-16 00:44:05 +0100] [23632] [INFO] Booting worker with pid: 23632
[2025-04-16 00:57:49 +0100] [23889] [INFO] Starting gunicorn 23.0.0
[2025-04-16 00:57:49 +0100] [23889] [ERROR] Connection in use: ('192.168.54.204', 7890)
[2025-04-16 00:57:49 +0100] [23889] [ERROR] connection to ('192.168.54.204', 7890) failed: [Errno 48] Address already in use
[2025-04-16 00:57:50 +0100] [23889] [ERROR] Connection in use: ('192.168.54.204', 7890)
[2025-04-16 00:57:50 +0100] [23889] [ERROR] connection to ('192.168.54.204', 7890) failed: [Errno 48] Address already in use
[2025-04-16 00:57:51 +0100] [23889] [ERROR] Connection in use: ('192.168.54.204', 7890)
[2025-04-16 00:57:51 +0100] [23889] [ERROR] connection to ('192.168.54.204', 7890) failed: [Errno 48] Address already in use
[2025-04-16 00:57:52 +0100] [23889] [ERROR] Connection in use: ('192.168.54.204', 7890)
[2025-04-16 00:57:52 +0100] [23889] [ERROR] connection to ('192.168.54.204', 7890) failed: [Errno 48] Address already in use
[2025-04-16 00:57:53 +0100] [23889] [ERROR] Connection in use: ('192.168.54.204', 7890)
[2025-04-16 00:57:53 +0100] [23889] [ERROR] connection to ('192.168.54.204', 7890) failed: [Errno 48] Address already in use
[2025-04-16 00:57:54 +0100] [23889] [ERROR] Can't connect to ('192.168.54.204', 7890)
[2025-04-16 01:00:46 +0100] [22924] [CRITICAL] WORKER TIMEOUT (pid:22926)
[2025-04-16 01:00:46 +0100] [22926] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-16 01:00:46 +0100] [22926] [INFO] Worker exiting (pid: 22926)
[2025-04-16 01:00:46 +0100] [22924] [ERROR] Worker (pid:22926) exited with code 120
[2025-04-16 01:00:46 +0100] [22924] [ERROR] Worker (pid:22926) exited with code 120.
[2025-04-16 01:00:46 +0100] [23945] [INFO] Booting worker with pid: 23945
[2025-04-16 10:15:05 +0100] [22924] [INFO] Handling signal: winch
[2025-04-16 10:33:10 +0100] [22924] [INFO] Handling signal: winch
[2025-04-16 10:39:30 +0100] [22924] [INFO] Handling signal: int
[2025-04-16 10:39:31 +0100] [23632] [INFO] Worker exiting (pid: 23632)
[2025-04-16 10:39:31 +0100] [23945] [INFO] Worker exiting (pid: 23945)
[2025-04-16 10:39:31 +0100] [22963] [INFO] Worker exiting (pid: 22963)
[2025-04-16 10:39:31 +0100] [23324] [INFO] Worker exiting (pid: 23324)
[2025-04-16 10:39:31 +0100] [22924] [ERROR] Worker (pid:23632) exited with code 120
[2025-04-16 10:39:31 +0100] [22924] [ERROR] Worker (pid:23632) exited with code 120.
[2025-04-16 10:39:31 +0100] [22924] [ERROR] Worker (pid:23324) exited with code 120
[2025-04-16 10:39:31 +0100] [22924] [ERROR] Worker (pid:23324) exited with code 120.
[2025-04-16 10:39:31 +0100] [22924] [ERROR] Worker (pid:22963) exited with code 120
[2025-04-16 10:39:31 +0100] [22924] [ERROR] Worker (pid:22963) exited with code 120.
[2025-04-16 10:39:31 +0100] [22924] [INFO] Shutting down: Master
[2025-04-16 22:45:00 +0100] [39539] [INFO] Starting gunicorn 23.0.0
[2025-04-16 22:45:00 +0100] [39539] [INFO] Listening at: http://192.168.54.204:7890 (39539)
[2025-04-16 22:45:00 +0100] [39539] [INFO] Using worker: sync
[2025-04-16 22:45:00 +0100] [39540] [INFO] Booting worker with pid: 39540
[2025-04-16 22:45:00 +0100] [39541] [INFO] Booting worker with pid: 39541
[2025-04-16 22:45:00 +0100] [39542] [INFO] Booting worker with pid: 39542
[2025-04-16 22:45:00 +0100] [39543] [INFO] Booting worker with pid: 39543
[2025-04-17 00:42:09 +0100] [39539] [INFO] Handling signal: int
[2025-04-17 00:42:09 +0100] [39540] [INFO] Worker exiting (pid: 39540)
[2025-04-17 00:42:09 +0100] [39542] [INFO] Worker exiting (pid: 39542)
[2025-04-17 00:42:09 +0100] [39541] [INFO] Worker exiting (pid: 39541)
[2025-04-17 00:42:09 +0100] [39543] [INFO] Worker exiting (pid: 39543)
[2025-04-17 00:42:09 +0100] [39539] [ERROR] Worker (pid:39540) exited with code 120
[2025-04-17 00:42:09 +0100] [39539] [ERROR] Worker (pid:39540) exited with code 120.
[2025-04-17 00:42:09 +0100] [39539] [INFO] Shutting down: Master
[2025-04-17 01:27:37 +0100] [44817] [INFO] Starting gunicorn 23.0.0
[2025-04-17 01:27:37 +0100] [44817] [INFO] Listening at: http://192.168.54.204:7890 (44817)
[2025-04-17 01:27:37 +0100] [44817] [INFO] Using worker: sync
[2025-04-17 01:27:37 +0100] [44818] [INFO] Booting worker with pid: 44818
[2025-04-17 01:27:37 +0100] [44819] [INFO] Booting worker with pid: 44819
[2025-04-17 01:27:37 +0100] [44820] [INFO] Booting worker with pid: 44820
[2025-04-17 01:27:37 +0100] [44821] [INFO] Booting worker with pid: 44821
[2025-04-17 01:32:16 +0100] [44817] [INFO] Handling signal: int
[2025-04-17 01:32:16 +0100] [44820] [INFO] Worker exiting (pid: 44820)
[2025-04-17 01:32:16 +0100] [44821] [INFO] Worker exiting (pid: 44821)
[2025-04-17 01:32:16 +0100] [44819] [INFO] Worker exiting (pid: 44819)
[2025-04-17 01:32:16 +0100] [44818] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-17 01:32:16 +0100] [44818] [INFO] Worker exiting (pid: 44818)
[2025-04-17 01:32:16 +0100] [44817] [ERROR] Worker (pid:44821) exited with code 120
[2025-04-17 01:32:16 +0100] [44817] [ERROR] Worker (pid:44821) exited with code 120.
[2025-04-17 01:32:16 +0100] [44817] [ERROR] Worker (pid:44819) exited with code 120
[2025-04-17 01:32:16 +0100] [44817] [ERROR] Worker (pid:44819) exited with code 120.
[2025-04-17 01:32:16 +0100] [44817] [INFO] Shutting down: Master
[2025-04-17 01:34:27 +0100] [45034] [INFO] Starting gunicorn 23.0.0
[2025-04-17 01:34:27 +0100] [45034] [INFO] Listening at: http://192.168.54.204:7890 (45034)
[2025-04-17 01:34:27 +0100] [45034] [INFO] Using worker: sync
[2025-04-17 01:34:27 +0100] [45035] [INFO] Booting worker with pid: 45035
[2025-04-17 01:34:28 +0100] [45036] [INFO] Booting worker with pid: 45036
[2025-04-17 01:34:28 +0100] [45037] [INFO] Booting worker with pid: 45037
[2025-04-17 01:34:28 +0100] [45038] [INFO] Booting worker with pid: 45038
[2025-04-17 07:11:58 +0100] [45034] [INFO] Handling signal: winch
[2025-04-17 09:24:13 +0100] [45034] [INFO] Handling signal: winch
[2025-04-17 09:25:37 +0100] [45034] [INFO] Handling signal: winch
[2025-04-17 09:26:55 +0100] [45034] [INFO] Handling signal: winch
[2025-04-17 09:30:59 +0100] [45034] [INFO] Handling signal: term
[2025-04-17 09:30:59 +0100] [45036] [INFO] Worker exiting (pid: 45036)
[2025-04-17 09:30:59 +0100] [45038] [INFO] Worker exiting (pid: 45038)
[2025-04-17 09:30:59 +0100] [45035] [INFO] Worker exiting (pid: 45035)
[2025-04-17 09:30:59 +0100] [45037] [INFO] Worker exiting (pid: 45037)
[2025-04-17 09:31:00 +0100] [45034] [INFO] Shutting down: Master
[2025-04-17 09:31:14 +0100] [46230] [INFO] Starting gunicorn 23.0.0
[2025-04-17 09:31:14 +0100] [46230] [INFO] Listening at: http://192.168.253.133:7890 (46230)
[2025-04-17 09:31:14 +0100] [46230] [INFO] Using worker: sync
[2025-04-17 09:31:14 +0100] [46231] [INFO] Booting worker with pid: 46231
[2025-04-17 09:31:14 +0100] [46232] [INFO] Booting worker with pid: 46232
[2025-04-17 09:31:14 +0100] [46233] [INFO] Booting worker with pid: 46233
[2025-04-17 09:31:14 +0100] [46234] [INFO] Booting worker with pid: 46234
[2025-04-17 09:46:10 +0100] [46230] [INFO] Handling signal: int
[2025-04-17 09:46:10 +0100] [46233] [INFO] Worker exiting (pid: 46233)
[2025-04-17 09:46:10 +0100] [46231] [INFO] Worker exiting (pid: 46231)
[2025-04-17 09:46:10 +0100] [46232] [INFO] Worker exiting (pid: 46232)
[2025-04-17 09:46:10 +0100] [46234] [INFO] Worker exiting (pid: 46234)
[2025-04-17 09:46:11 +0100] [46230] [INFO] Shutting down: Master
[2025-04-17 09:46:41 +0100] [46558] [INFO] Starting gunicorn 23.0.0
[2025-04-17 09:46:41 +0100] [46558] [INFO] Listening at: http://192.168.253.133:7890 (46558)
[2025-04-17 09:46:41 +0100] [46558] [INFO] Using worker: sync
[2025-04-17 09:46:41 +0100] [46559] [INFO] Booting worker with pid: 46559
[2025-04-17 09:46:41 +0100] [46560] [INFO] Booting worker with pid: 46560
[2025-04-17 09:46:41 +0100] [46561] [INFO] Booting worker with pid: 46561
[2025-04-17 09:46:41 +0100] [46562] [INFO] Booting worker with pid: 46562
[2025-04-17 09:48:16 +0100] [46619] [INFO] Starting gunicorn 23.0.0
[2025-04-17 09:48:16 +0100] [46619] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-17 09:48:16 +0100] [46619] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-17 09:48:17 +0100] [46619] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-17 09:48:17 +0100] [46619] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-17 09:48:18 +0100] [46619] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-17 09:48:18 +0100] [46619] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-17 09:48:19 +0100] [46619] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-17 09:48:19 +0100] [46619] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-17 09:48:20 +0100] [46619] [ERROR] Connection in use: ('192.168.253.133', 7890)
[2025-04-17 09:48:20 +0100] [46619] [ERROR] connection to ('192.168.253.133', 7890) failed: [Errno 48] Address already in use
[2025-04-17 09:48:21 +0100] [46619] [ERROR] Can't connect to ('192.168.253.133', 7890)
[2025-04-17 10:04:26 +0100] [46558] [INFO] Handling signal: int
[2025-04-17 10:04:26 +0100] [46560] [INFO] Worker exiting (pid: 46560)
[2025-04-17 10:04:26 +0100] [46561] [INFO] Worker exiting (pid: 46561)
[2025-04-17 10:04:26 +0100] [46562] [INFO] Worker exiting (pid: 46562)
[2025-04-17 10:04:26 +0100] [46559] [INFO] Worker exiting (pid: 46559)
[2025-04-17 10:04:27 +0100] [46558] [INFO] Shutting down: Master
[2025-04-17 10:04:55 +0100] [47101] [INFO] Starting gunicorn 23.0.0
[2025-04-17 10:04:55 +0100] [47101] [INFO] Listening at: http://192.168.253.133:7890 (47101)
[2025-04-17 10:04:55 +0100] [47101] [INFO] Using worker: sync
[2025-04-17 10:04:55 +0100] [47102] [INFO] Booting worker with pid: 47102
[2025-04-17 10:04:55 +0100] [47103] [INFO] Booting worker with pid: 47103
[2025-04-17 10:04:55 +0100] [47104] [INFO] Booting worker with pid: 47104
[2025-04-17 10:04:55 +0100] [47105] [INFO] Booting worker with pid: 47105
[2025-04-17 11:52:19 +0100] [47101] [CRITICAL] WORKER TIMEOUT (pid:47103)
[2025-04-17 11:52:19 +0100] [47103] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 11:52:19 +0100] [47103] [INFO] Worker exiting (pid: 47103)
[2025-04-17 11:52:19 +0100] [47845] [INFO] Booting worker with pid: 47845
[2025-04-17 12:19:35 +0100] [47101] [CRITICAL] WORKER TIMEOUT (pid:47104)
[2025-04-17 12:19:35 +0100] [47101] [CRITICAL] WORKER TIMEOUT (pid:47105)
[2025-04-17 12:19:35 +0100] [47105] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 12:19:35 +0100] [47105] [INFO] Worker exiting (pid: 47105)
[2025-04-17 12:19:35 +0100] [47104] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 12:19:35 +0100] [47104] [INFO] Worker exiting (pid: 47104)
[2025-04-17 12:19:36 +0100] [48483] [INFO] Booting worker with pid: 48483
[2025-04-17 12:19:36 +0100] [47101] [ERROR] Worker (pid:47104) was sent SIGKILL! Perhaps out of memory?
[2025-04-17 12:19:36 +0100] [48484] [INFO] Booting worker with pid: 48484
[2025-04-17 15:24:24 +0100] [47101] [INFO] Handling signal: int
[2025-04-17 15:24:24 +0100] [47102] [INFO] Worker exiting (pid: 47102)
[2025-04-17 15:24:24 +0100] [47845] [INFO] Worker exiting (pid: 47845)
[2025-04-17 15:24:24 +0100] [48483] [INFO] Worker exiting (pid: 48483)
[2025-04-17 15:24:24 +0100] [48484] [INFO] Worker exiting (pid: 48484)
[2025-04-17 15:24:25 +0100] [47101] [INFO] Shutting down: Master
[2025-04-17 20:50:13 +0100] [61224] [INFO] Starting gunicorn 23.0.0
[2025-04-17 20:50:13 +0100] [61224] [INFO] Listening at: http://192.168.158.204:7890 (61224)
[2025-04-17 20:50:13 +0100] [61224] [INFO] Using worker: sync
[2025-04-17 20:50:13 +0100] [61225] [INFO] Booting worker with pid: 61225
[2025-04-17 20:50:13 +0100] [61226] [INFO] Booting worker with pid: 61226
[2025-04-17 20:50:13 +0100] [61227] [INFO] Booting worker with pid: 61227
[2025-04-17 20:50:13 +0100] [61228] [INFO] Booting worker with pid: 61228
[2025-04-17 21:12:49 +0100] [61224] [CRITICAL] WORKER TIMEOUT (pid:61227)
[2025-04-17 21:12:49 +0100] [61227] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 21:12:49 +0100] [61227] [INFO] Worker exiting (pid: 61227)
[2025-04-17 21:12:49 +0100] [61608] [INFO] Booting worker with pid: 61608
[2025-04-17 21:18:42 +0100] [61224] [CRITICAL] WORKER TIMEOUT (pid:61225)
[2025-04-17 21:18:42 +0100] [61225] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 21:18:42 +0100] [61225] [INFO] Worker exiting (pid: 61225)
[2025-04-17 21:18:42 +0100] [61706] [INFO] Booting worker with pid: 61706
[2025-04-17 21:27:51 +0100] [61224] [INFO] Handling signal: int
[2025-04-17 21:27:51 +0100] [61228] [INFO] Worker exiting (pid: 61228)
[2025-04-17 21:27:51 +0100] [61706] [INFO] Worker exiting (pid: 61706)
[2025-04-17 21:27:51 +0100] [61608] [INFO] Worker exiting (pid: 61608)
[2025-04-17 21:27:51 +0100] [61226] [INFO] Worker exiting (pid: 61226)
[2025-04-17 21:27:52 +0100] [61224] [INFO] Shutting down: Master
[2025-04-17 21:28:52 +0100] [61883] [INFO] Starting gunicorn 23.0.0
[2025-04-17 21:28:52 +0100] [61883] [INFO] Listening at: http://192.168.158.204:7890 (61883)
[2025-04-17 21:28:52 +0100] [61883] [INFO] Using worker: sync
[2025-04-17 21:28:52 +0100] [61884] [INFO] Booting worker with pid: 61884
[2025-04-17 21:28:52 +0100] [61885] [INFO] Booting worker with pid: 61885
[2025-04-17 21:28:52 +0100] [61886] [INFO] Booting worker with pid: 61886
[2025-04-17 21:28:52 +0100] [61887] [INFO] Booting worker with pid: 61887
[2025-04-17 21:31:01 +0100] [61883] [CRITICAL] WORKER TIMEOUT (pid:61885)
[2025-04-17 21:31:01 +0100] [61885] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 21:31:01 +0100] [61885] [INFO] Worker exiting (pid: 61885)
[2025-04-17 21:31:01 +0100] [61927] [INFO] Booting worker with pid: 61927
[2025-04-17 21:42:05 +0100] [61883] [CRITICAL] WORKER TIMEOUT (pid:61927)
[2025-04-17 21:42:05 +0100] [61927] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 21:42:05 +0100] [61927] [INFO] Worker exiting (pid: 61927)
[2025-04-17 21:42:05 +0100] [62114] [INFO] Booting worker with pid: 62114
[2025-04-17 21:42:50 +0100] [61883] [CRITICAL] WORKER TIMEOUT (pid:61884)
[2025-04-17 21:42:50 +0100] [61884] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 21:42:50 +0100] [61884] [INFO] Worker exiting (pid: 61884)
[2025-04-17 21:42:50 +0100] [62125] [INFO] Booting worker with pid: 62125
[2025-04-17 21:46:17 +0100] [61883] [CRITICAL] WORKER TIMEOUT (pid:61886)
[2025-04-17 21:46:17 +0100] [61886] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 21:46:17 +0100] [61886] [INFO] Worker exiting (pid: 61886)
[2025-04-17 21:46:17 +0100] [62199] [INFO] Booting worker with pid: 62199
[2025-04-17 21:46:46 +0100] [61883] [CRITICAL] WORKER TIMEOUT (pid:62125)
[2025-04-17 21:46:46 +0100] [62125] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 21:46:46 +0100] [62125] [INFO] Worker exiting (pid: 62125)
[2025-04-17 21:46:46 +0100] [62225] [INFO] Booting worker with pid: 62225
[2025-04-17 22:24:14 +0100] [61883] [INFO] Handling signal: winch
[2025-04-17 22:24:22 +0100] [61883] [INFO] Handling signal: winch
[2025-04-17 22:29:13 +0100] [67819] [INFO] Starting gunicorn 23.0.0
[2025-04-17 22:29:13 +0100] [67819] [ERROR] Invalid address: ('192.168.158.204', 7890)
[2025-04-17 22:29:13 +0100] [67819] [ERROR] connection to ('192.168.158.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-17 22:29:14 +0100] [67819] [ERROR] Invalid address: ('192.168.158.204', 7890)
[2025-04-17 22:29:14 +0100] [67819] [ERROR] connection to ('192.168.158.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-17 22:29:15 +0100] [67819] [ERROR] Invalid address: ('192.168.158.204', 7890)
[2025-04-17 22:29:15 +0100] [67819] [ERROR] connection to ('192.168.158.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-17 22:29:16 +0100] [67819] [ERROR] Invalid address: ('192.168.158.204', 7890)
[2025-04-17 22:29:16 +0100] [67819] [ERROR] connection to ('192.168.158.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-17 22:29:17 +0100] [67819] [ERROR] Invalid address: ('192.168.158.204', 7890)
[2025-04-17 22:29:17 +0100] [67819] [ERROR] connection to ('192.168.158.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-17 22:29:18 +0100] [67819] [ERROR] Can't connect to ('192.168.158.204', 7890)
[2025-04-17 22:43:29 +0100] [61883] [INFO] Handling signal: winch
[2025-04-17 22:43:34 +0100] [61883] [INFO] Handling signal: winch
[2025-04-17 22:47:00 +0100] [69479] [INFO] Starting gunicorn 23.0.0
[2025-04-17 22:47:00 +0100] [69479] [INFO] Listening at: http://192.168.170.204:7890 (69479)
[2025-04-17 22:47:00 +0100] [69479] [INFO] Using worker: sync
[2025-04-17 22:47:00 +0100] [69480] [INFO] Booting worker with pid: 69480
[2025-04-17 22:47:00 +0100] [69481] [INFO] Booting worker with pid: 69481
[2025-04-17 22:47:00 +0100] [69482] [INFO] Booting worker with pid: 69482
[2025-04-17 22:47:00 +0100] [69483] [INFO] Booting worker with pid: 69483
[2025-04-17 22:48:10 +0100] [69479] [INFO] Handling signal: int
[2025-04-17 22:48:10 +0100] [61883] [INFO] Handling signal: int
[2025-04-17 22:48:10 +0100] [69482] [INFO] Worker exiting (pid: 69482)
[2025-04-17 22:48:10 +0100] [69480] [INFO] Worker exiting (pid: 69480)
[2025-04-17 22:48:10 +0100] [69483] [INFO] Worker exiting (pid: 69483)
[2025-04-17 22:48:10 +0100] [69481] [INFO] Worker exiting (pid: 69481)
[2025-04-17 22:48:10 +0100] [62114] [INFO] Worker exiting (pid: 62114)
[2025-04-17 22:48:10 +0100] [61887] [INFO] Worker exiting (pid: 61887)
[2025-04-17 22:48:10 +0100] [62199] [INFO] Worker exiting (pid: 62199)
[2025-04-17 22:48:10 +0100] [62225] [INFO] Worker exiting (pid: 62225)
[2025-04-17 22:48:10 +0100] [69479] [INFO] Shutting down: Master
[2025-04-17 22:48:10 +0100] [61883] [INFO] Shutting down: Master
[2025-04-17 22:48:29 +0100] [69549] [INFO] Starting gunicorn 23.0.0
[2025-04-17 22:48:29 +0100] [69549] [INFO] Listening at: http://192.168.170.204:7890 (69549)
[2025-04-17 22:48:29 +0100] [69549] [INFO] Using worker: sync
[2025-04-17 22:48:29 +0100] [69550] [INFO] Booting worker with pid: 69550
[2025-04-17 22:48:29 +0100] [69552] [INFO] Booting worker with pid: 69552
[2025-04-17 22:48:29 +0100] [69553] [INFO] Booting worker with pid: 69553
[2025-04-17 22:48:29 +0100] [69555] [INFO] Booting worker with pid: 69555
[2025-04-17 23:44:27 +0100] [69549] [INFO] Handling signal: int
[2025-04-17 23:44:27 +0100] [69555] [INFO] Worker exiting (pid: 69555)
[2025-04-17 23:44:27 +0100] [69552] [INFO] Worker exiting (pid: 69552)
[2025-04-17 23:44:27 +0100] [69550] [INFO] Worker exiting (pid: 69550)
[2025-04-17 23:44:27 +0100] [69553] [INFO] Worker exiting (pid: 69553)
[2025-04-17 23:44:27 +0100] [69549] [INFO] Shutting down: Master
[2025-04-17 23:45:46 +0100] [71868] [INFO] Starting gunicorn 23.0.0
[2025-04-17 23:45:46 +0100] [71868] [INFO] Listening at: http://192.168.170.204:7890 (71868)
[2025-04-17 23:45:46 +0100] [71868] [INFO] Using worker: sync
[2025-04-17 23:45:46 +0100] [71869] [INFO] Booting worker with pid: 71869
[2025-04-17 23:45:46 +0100] [71870] [INFO] Booting worker with pid: 71870
[2025-04-17 23:45:46 +0100] [71871] [INFO] Booting worker with pid: 71871
[2025-04-17 23:45:46 +0100] [71872] [INFO] Booting worker with pid: 71872
[2025-04-17 23:48:00 +0100] [71868] [CRITICAL] WORKER TIMEOUT (pid:71871)
[2025-04-17 23:48:00 +0100] [71871] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 23:48:00 +0100] [71871] [INFO] Worker exiting (pid: 71871)
[2025-04-17 23:48:00 +0100] [71971] [INFO] Booting worker with pid: 71971
[2025-04-17 23:52:29 +0100] [71868] [CRITICAL] WORKER TIMEOUT (pid:71971)
[2025-04-17 23:52:29 +0100] [71971] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 23:52:29 +0100] [71971] [INFO] Worker exiting (pid: 71971)
[2025-04-17 23:52:30 +0100] [72087] [INFO] Booting worker with pid: 72087
[2025-04-17 23:55:39 +0100] [71868] [CRITICAL] WORKER TIMEOUT (pid:71869)
[2025-04-17 23:55:39 +0100] [71869] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 23:55:39 +0100] [71869] [INFO] Worker exiting (pid: 71869)
[2025-04-17 23:55:39 +0100] [72192] [INFO] Booting worker with pid: 72192
[2025-04-18 00:31:42 +0100] [71868] [INFO] Handling signal: int
[2025-04-18 00:31:42 +0100] [72192] [INFO] Worker exiting (pid: 72192)
[2025-04-18 00:31:42 +0100] [71872] [INFO] Worker exiting (pid: 71872)
[2025-04-18 00:31:42 +0100] [72087] [INFO] Worker exiting (pid: 72087)
[2025-04-18 00:31:42 +0100] [71870] [INFO] Worker exiting (pid: 71870)
[2025-04-18 00:31:42 +0100] [71868] [INFO] Shutting down: Master
[2025-04-18 00:32:24 +0100] [72952] [INFO] Starting gunicorn 23.0.0
[2025-04-18 00:32:24 +0100] [72952] [INFO] Listening at: http://192.168.170.204:7890 (72952)
[2025-04-18 00:32:24 +0100] [72952] [INFO] Using worker: sync
[2025-04-18 00:32:24 +0100] [72953] [INFO] Booting worker with pid: 72953
[2025-04-18 00:32:24 +0100] [72954] [INFO] Booting worker with pid: 72954
[2025-04-18 00:32:24 +0100] [72955] [INFO] Booting worker with pid: 72955
[2025-04-18 00:32:24 +0100] [72956] [INFO] Booting worker with pid: 72956
[2025-04-18 09:59:55 +0100] [72952] [INFO] Handling signal: winch
[2025-04-18 10:15:16 +0100] [72952] [INFO] Handling signal: winch
[2025-04-18 10:18:35 +0100] [72952] [INFO] Handling signal: winch
[2025-04-19 15:02:55 +0100] [72952] [INFO] Handling signal: winch
[2025-04-20 00:04:22 +0100] [72952] [INFO] Handling signal: winch
[2025-04-20 00:04:29 +0100] [72952] [INFO] Handling signal: winch
[2025-04-20 01:49:41 +0100] [89676] [INFO] Starting gunicorn 23.0.0
[2025-04-20 01:49:41 +0100] [89676] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:49:41 +0100] [89676] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:49:42 +0100] [89676] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:49:42 +0100] [89676] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:49:43 +0100] [89676] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:49:43 +0100] [89676] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:49:44 +0100] [89676] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:49:44 +0100] [89676] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:49:45 +0100] [89676] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:49:45 +0100] [89676] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:49:46 +0100] [89676] [ERROR] Can't connect to ('192.168.170.204', 7890)
[2025-04-20 01:56:42 +0100] [89821] [INFO] Starting gunicorn 23.0.0
[2025-04-20 01:56:42 +0100] [89821] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:56:42 +0100] [89821] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:56:43 +0100] [89821] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:56:43 +0100] [89821] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:56:44 +0100] [89821] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:56:44 +0100] [89821] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:56:45 +0100] [89821] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:56:45 +0100] [89821] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:56:46 +0100] [89821] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:56:46 +0100] [89821] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:56:47 +0100] [89821] [ERROR] Can't connect to ('192.168.170.204', 7890)
[2025-04-20 01:57:16 +0100] [89865] [INFO] Starting gunicorn 23.0.0
[2025-04-20 01:57:16 +0100] [89865] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:57:16 +0100] [89865] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:57:17 +0100] [89865] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:57:17 +0100] [89865] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:57:18 +0100] [89865] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:57:18 +0100] [89865] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:57:19 +0100] [89865] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:57:19 +0100] [89865] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:57:20 +0100] [89865] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:57:20 +0100] [89865] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:57:21 +0100] [89865] [ERROR] Can't connect to ('192.168.170.204', 7890)
[2025-04-20 01:58:30 +0100] [89918] [INFO] Starting gunicorn 23.0.0
[2025-04-20 01:58:30 +0100] [89918] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:58:30 +0100] [89918] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:58:31 +0100] [89918] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:58:31 +0100] [89918] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:58:32 +0100] [89918] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:58:32 +0100] [89918] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:58:33 +0100] [89918] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:58:33 +0100] [89918] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:58:34 +0100] [89918] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:58:34 +0100] [89918] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:58:35 +0100] [89918] [ERROR] Can't connect to ('192.168.170.204', 7890)
[2025-04-20 01:59:04 +0100] [72952] [INFO] Handling signal: int
[2025-04-20 01:59:04 +0100] [72954] [INFO] Worker exiting (pid: 72954)
[2025-04-20 01:59:04 +0100] [72953] [INFO] Worker exiting (pid: 72953)
[2025-04-20 01:59:04 +0100] [72955] [INFO] Worker exiting (pid: 72955)
[2025-04-20 01:59:04 +0100] [72956] [INFO] Worker exiting (pid: 72956)
[2025-04-20 01:59:05 +0100] [72952] [INFO] Shutting down: Master
[2025-04-20 01:59:50 +0100] [89965] [INFO] Starting gunicorn 23.0.0
[2025-04-20 01:59:50 +0100] [89965] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:59:50 +0100] [89965] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:59:51 +0100] [89965] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:59:51 +0100] [89965] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:59:52 +0100] [89965] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:59:52 +0100] [89965] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:59:53 +0100] [89965] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:59:53 +0100] [89965] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:59:54 +0100] [89965] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 01:59:54 +0100] [89965] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 01:59:55 +0100] [89965] [ERROR] Can't connect to ('192.168.170.204', 7890)
[2025-04-20 02:29:42 +0100] [90686] [INFO] Starting gunicorn 23.0.0
[2025-04-20 02:29:42 +0100] [90686] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 02:29:42 +0100] [90686] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 02:29:43 +0100] [90686] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 02:29:43 +0100] [90686] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 02:29:44 +0100] [90686] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 02:29:44 +0100] [90686] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 02:29:45 +0100] [90686] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 02:29:45 +0100] [90686] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 02:29:46 +0100] [90686] [ERROR] Invalid address: ('192.168.170.204', 7890)
[2025-04-20 02:29:46 +0100] [90686] [ERROR] connection to ('192.168.170.204', 7890) failed: [Errno 49] Can't assign requested address
[2025-04-20 02:29:47 +0100] [90686] [ERROR] Can't connect to ('192.168.170.204', 7890)
[2025-04-20 02:31:48 +0100] [90789] [INFO] Starting gunicorn 23.0.0
[2025-04-20 02:31:48 +0100] [90789] [INFO] Listening at: http://192.168.89.204:7890 (90789)
[2025-04-20 02:31:48 +0100] [90789] [INFO] Using worker: sync
[2025-04-20 02:31:48 +0100] [90790] [INFO] Booting worker with pid: 90790
[2025-04-20 02:31:48 +0100] [90791] [INFO] Booting worker with pid: 90791
[2025-04-20 02:31:48 +0100] [90792] [INFO] Booting worker with pid: 90792
[2025-04-20 02:31:48 +0100] [90793] [INFO] Booting worker with pid: 90793
[2025-04-20 03:10:32 +0100] [90789] [INFO] Handling signal: term
[2025-04-20 03:10:32 +0100] [90791] [INFO] Worker exiting (pid: 90791)
[2025-04-20 03:10:32 +0100] [90792] [INFO] Worker exiting (pid: 90792)
[2025-04-20 03:10:32 +0100] [90790] [INFO] Worker exiting (pid: 90790)
[2025-04-20 03:10:32 +0100] [90793] [INFO] Worker exiting (pid: 90793)
[2025-04-20 03:10:33 +0100] [90789] [INFO] Shutting down: Master
[2025-04-20 03:10:36 +0100] [91850] [INFO] Starting gunicorn 23.0.0
[2025-04-20 03:10:36 +0100] [91850] [INFO] Listening at: http://192.168.89.204:7890 (91850)
[2025-04-20 03:10:36 +0100] [91850] [INFO] Using worker: sync
[2025-04-20 03:10:36 +0100] [91851] [INFO] Booting worker with pid: 91851
[2025-04-20 03:10:36 +0100] [91852] [INFO] Booting worker with pid: 91852
[2025-04-20 03:10:36 +0100] [91853] [INFO] Booting worker with pid: 91853
[2025-04-20 03:10:36 +0100] [91854] [INFO] Booting worker with pid: 91854
[2025-04-20 03:15:40 +0100] [91850] [INFO] Handling signal: term
[2025-04-20 03:15:40 +0100] [91853] [INFO] Worker exiting (pid: 91853)
[2025-04-20 03:15:40 +0100] [91852] [INFO] Worker exiting (pid: 91852)
[2025-04-20 03:15:40 +0100] [91851] [INFO] Worker exiting (pid: 91851)
[2025-04-20 03:15:40 +0100] [91854] [INFO] Worker exiting (pid: 91854)
[2025-04-20 03:15:40 +0100] [91850] [INFO] Shutting down: Master
[2025-04-20 21:51:18 +0100] [98030] [INFO] Starting gunicorn 23.0.0
[2025-04-20 21:51:18 +0100] [98030] [INFO] Listening at: http://192.168.89.204:7890 (98030)
[2025-04-20 21:51:18 +0100] [98030] [INFO] Using worker: sync
[2025-04-20 21:51:18 +0100] [98031] [INFO] Booting worker with pid: 98031
[2025-04-20 21:51:18 +0100] [98034] [INFO] Booting worker with pid: 98034
[2025-04-20 21:51:18 +0100] [98035] [INFO] Booting worker with pid: 98035
[2025-04-20 21:51:18 +0100] [98036] [INFO] Booting worker with pid: 98036
[2025-04-24 12:17:11 +0100] [60958] [INFO] Starting gunicorn 23.0.0
[2025-04-24 12:17:12 +0100] [60958] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:17:12 +0100] [60958] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:17:13 +0100] [60958] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:17:13 +0100] [60958] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:17:14 +0100] [60958] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:17:14 +0100] [60958] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:17:15 +0100] [60958] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:17:15 +0100] [60958] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:17:16 +0100] [60958] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:17:16 +0100] [60958] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:17:17 +0100] [60958] [ERROR] Can't connect to ('192.168.61.204', 5678)
[2025-04-24 12:18:31 +0100] [61011] [INFO] Starting gunicorn 23.0.0
[2025-04-24 12:18:31 +0100] [61011] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:18:31 +0100] [61011] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:18:32 +0100] [61011] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:18:32 +0100] [61011] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:18:33 +0100] [61011] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:18:33 +0100] [61011] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:18:34 +0100] [61011] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:18:34 +0100] [61011] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:18:35 +0100] [61011] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:18:35 +0100] [61011] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:18:36 +0100] [61011] [ERROR] Can't connect to ('192.168.61.204', 5678)
[2025-04-24 12:19:31 +0100] [61036] [INFO] Starting gunicorn 23.0.0
[2025-04-24 12:19:31 +0100] [61036] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:19:31 +0100] [61036] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:19:32 +0100] [61036] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:19:32 +0100] [61036] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:19:33 +0100] [61036] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:19:33 +0100] [61036] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:19:34 +0100] [61036] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:19:34 +0100] [61036] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:19:35 +0100] [61036] [ERROR] Invalid address: ('192.168.61.204', 5678)
[2025-04-24 12:19:35 +0100] [61036] [ERROR] connection to ('192.168.61.204', 5678) failed: [Errno 49] Can't assign requested address
[2025-04-24 12:19:36 +0100] [61036] [ERROR] Can't connect to ('192.168.61.204', 5678)
[2025-04-24 12:22:14 +0100] [61134] [INFO] Starting gunicorn 23.0.0
[2025-04-24 12:22:14 +0100] [61134] [INFO] Listening at: http://192.168.167.204:5678 (61134)
[2025-04-24 12:22:14 +0100] [61134] [INFO] Using worker: sync
[2025-04-24 12:22:14 +0100] [61135] [INFO] Booting worker with pid: 61135
[2025-04-24 12:22:14 +0100] [61136] [INFO] Booting worker with pid: 61136
[2025-04-24 12:22:14 +0100] [61137] [INFO] Booting worker with pid: 61137
[2025-04-24 12:22:14 +0100] [61138] [INFO] Booting worker with pid: 61138
[2025-04-24 14:20:15 +0100] [61134] [INFO] Handling signal: term
[2025-04-24 14:20:15 +0100] [61136] [INFO] Worker exiting (pid: 61136)
[2025-04-24 14:20:15 +0100] [61138] [INFO] Worker exiting (pid: 61138)
[2025-04-24 14:20:15 +0100] [61135] [INFO] Worker exiting (pid: 61135)
[2025-04-24 14:20:15 +0100] [61137] [INFO] Worker exiting (pid: 61137)
[2025-04-24 14:20:15 +0100] [61134] [INFO] Shutting down: Master
[2025-04-24 14:24:53 +0100] [65715] [INFO] Starting gunicorn 23.0.0
[2025-04-24 14:24:53 +0100] [65715] [INFO] Listening at: http://192.168.167.204:5678 (65715)
[2025-04-24 14:24:53 +0100] [65715] [INFO] Using worker: sync
[2025-04-24 14:24:53 +0100] [65716] [INFO] Booting worker with pid: 65716
[2025-04-24 14:24:53 +0100] [65717] [INFO] Booting worker with pid: 65717
[2025-04-24 14:24:53 +0100] [65718] [INFO] Booting worker with pid: 65718
[2025-04-24 14:24:53 +0100] [65719] [INFO] Booting worker with pid: 65719
[2025-04-24 14:25:13 +0100] [65715] [INFO] Handling signal: term
[2025-04-24 14:25:13 +0100] [65717] [INFO] Worker exiting (pid: 65717)
[2025-04-24 14:25:13 +0100] [65718] [INFO] Worker exiting (pid: 65718)
[2025-04-24 14:25:13 +0100] [65716] [INFO] Worker exiting (pid: 65716)
[2025-04-24 14:25:13 +0100] [65719] [INFO] Worker exiting (pid: 65719)
[2025-04-24 14:25:13 +0100] [65715] [INFO] Shutting down: Master
[2025-04-27 23:15:45 +0000] [35] [INFO] Starting gunicorn 23.0.0
[2025-04-27 23:15:45 +0000] [35] [ERROR] Invalid address: ('192.168.1.181', 9000)
[2025-04-27 23:15:45 +0000] [35] [ERROR] connection to ('192.168.1.181', 9000) failed: [Errno 99] Cannot assign requested address
[2025-04-27 23:15:46 +0000] [35] [ERROR] Invalid address: ('192.168.1.181', 9000)
[2025-04-27 23:15:46 +0000] [35] [ERROR] connection to ('192.168.1.181', 9000) failed: [Errno 99] Cannot assign requested address
[2025-04-27 23:15:47 +0000] [35] [ERROR] Invalid address: ('192.168.1.181', 9000)
[2025-04-27 23:15:47 +0000] [35] [ERROR] connection to ('192.168.1.181', 9000) failed: [Errno 99] Cannot assign requested address
[2025-04-27 23:15:48 +0000] [35] [ERROR] Invalid address: ('192.168.1.181', 9000)
[2025-04-27 23:15:48 +0000] [35] [ERROR] connection to ('192.168.1.181', 9000) failed: [Errno 99] Cannot assign requested address
[2025-04-27 23:15:49 +0000] [35] [ERROR] Invalid address: ('192.168.1.181', 9000)
[2025-04-27 23:15:49 +0000] [35] [ERROR] connection to ('192.168.1.181', 9000) failed: [Errno 99] Cannot assign requested address
[2025-04-27 23:15:50 +0000] [35] [ERROR] Can't connect to ('192.168.1.181', 9000)
[2025-04-28 08:09:19 +0000] [373] [INFO] Starting gunicorn 23.0.0
[2025-04-28 08:09:19 +0000] [373] [INFO] Listening at: http://172.18.0.4:9000 (373)
[2025-04-28 08:09:19 +0000] [373] [INFO] Using worker: sync
[2025-04-28 08:09:19 +0000] [374] [INFO] Booting worker with pid: 374
[2025-04-28 08:09:20 +0000] [375] [INFO] Booting worker with pid: 375
[2025-04-28 08:09:20 +0000] [376] [INFO] Booting worker with pid: 376
[2025-04-28 08:09:20 +0000] [377] [INFO] Booting worker with pid: 377
[2025-04-28 08:34:44 +0000] [65] [INFO] Starting gunicorn 23.0.0
[2025-04-28 08:34:44 +0000] [65] [INFO] Listening at: http://0.0.0.0:9000 (65)
[2025-04-28 08:34:44 +0000] [65] [INFO] Using worker: sync
[2025-04-28 08:34:44 +0000] [66] [INFO] Booting worker with pid: 66
[2025-04-28 08:34:44 +0000] [67] [INFO] Booting worker with pid: 67
[2025-04-28 08:34:44 +0000] [68] [INFO] Booting worker with pid: 68
[2025-04-28 08:34:44 +0000] [69] [INFO] Booting worker with pid: 69
[2025-04-28 09:43:42 +0000] [84] [INFO] Starting gunicorn 23.0.0
[2025-04-28 09:43:42 +0000] [84] [INFO] Listening at: http://0.0.0.0:9000 (84)
[2025-04-28 09:43:42 +0000] [84] [INFO] Using worker: sync
[2025-04-28 09:43:42 +0000] [85] [INFO] Booting worker with pid: 85
[2025-04-28 09:43:42 +0000] [86] [INFO] Booting worker with pid: 86
[2025-04-28 09:43:42 +0000] [87] [INFO] Booting worker with pid: 87
[2025-04-28 09:43:42 +0000] [88] [INFO] Booting worker with pid: 88
[2025-04-28 10:09:46 +0000] [39] [INFO] Starting gunicorn 23.0.0
[2025-04-28 10:09:46 +0000] [39] [INFO] Listening at: http://0.0.0.0:9000 (39)
[2025-04-28 10:09:46 +0000] [39] [INFO] Using worker: sync
[2025-04-28 10:09:46 +0000] [40] [INFO] Booting worker with pid: 40
[2025-04-28 10:09:46 +0000] [41] [INFO] Booting worker with pid: 41
[2025-04-28 10:09:46 +0000] [42] [INFO] Booting worker with pid: 42
[2025-04-28 10:09:46 +0000] [43] [INFO] Booting worker with pid: 43
[2025-04-28 10:28:12 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:40)
[2025-04-28 10:28:13 +0000] [40] [INFO] Worker exiting (pid: 40)
[2025-04-28 10:28:13 +0000] [39] [ERROR] Worker (pid:40) exited with code 1
[2025-04-28 10:28:13 +0000] [39] [ERROR] Worker (pid:40) exited with code 1.
[2025-04-28 10:28:13 +0000] [56] [INFO] Booting worker with pid: 56
[2025-04-28 12:47:38 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:56)
[2025-04-28 12:47:38 +0000] [56] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-28 12:47:38 +0000] [56] [INFO] Worker exiting (pid: 56)
[2025-04-28 12:47:38 +0000] [72] [INFO] Booting worker with pid: 72
[2025-04-28 13:37:37 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:41)
[2025-04-28 13:37:37 +0000] [41] [INFO] Worker exiting (pid: 41)
[2025-04-28 13:37:38 +0000] [39] [ERROR] Worker (pid:41) exited with code 1
[2025-04-28 13:37:38 +0000] [39] [ERROR] Worker (pid:41) exited with code 1.
[2025-04-28 13:37:38 +0000] [74] [INFO] Booting worker with pid: 74
[2025-04-28 13:45:27 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:42)
[2025-04-28 13:45:27 +0000] [42] [INFO] Worker exiting (pid: 42)
[2025-04-28 13:45:28 +0000] [39] [ERROR] Worker (pid:42) exited with code 1
[2025-04-28 13:45:28 +0000] [39] [ERROR] Worker (pid:42) exited with code 1.
[2025-04-28 13:45:28 +0000] [76] [INFO] Booting worker with pid: 76
[2025-04-28 14:47:40 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:72)
[2025-04-28 14:47:40 +0000] [72] [INFO] Worker exiting (pid: 72)
[2025-04-28 14:47:41 +0000] [39] [ERROR] Worker (pid:72) exited with code 1
[2025-04-28 14:47:41 +0000] [39] [ERROR] Worker (pid:72) exited with code 1.
[2025-04-28 14:47:41 +0000] [78] [INFO] Booting worker with pid: 78
[2025-04-28 14:52:17 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:43)
[2025-04-28 14:52:17 +0000] [43] [INFO] Worker exiting (pid: 43)
[2025-04-28 14:52:16 +0000] [39] [ERROR] Worker (pid:43) exited with code 1
[2025-04-28 14:52:16 +0000] [39] [ERROR] Worker (pid:43) exited with code 1.
[2025-04-28 14:52:16 +0000] [80] [INFO] Booting worker with pid: 80
[2025-04-28 15:11:30 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:74)
[2025-04-28 15:11:31 +0000] [74] [INFO] Worker exiting (pid: 74)
[2025-04-28 15:11:31 +0000] [39] [ERROR] Worker (pid:74) exited with code 1
[2025-04-28 15:11:31 +0000] [39] [ERROR] Worker (pid:74) exited with code 1.
[2025-04-28 15:11:31 +0000] [82] [INFO] Booting worker with pid: 82
[2025-04-28 17:04:56 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:76)
[2025-04-28 17:04:56 +0000] [76] [INFO] Worker exiting (pid: 76)
[2025-04-28 17:04:57 +0000] [39] [ERROR] Worker (pid:76) exited with code 1
[2025-04-28 17:04:57 +0000] [39] [ERROR] Worker (pid:76) exited with code 1.
[2025-04-28 17:04:57 +0000] [84] [INFO] Booting worker with pid: 84
[2025-04-28 17:55:37 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:80)
[2025-04-28 17:55:38 +0000] [80] [INFO] Worker exiting (pid: 80)
[2025-04-28 17:55:40 +0000] [39] [ERROR] Worker (pid:80) exited with code 1
[2025-04-28 17:55:40 +0000] [39] [ERROR] Worker (pid:80) exited with code 1.
[2025-04-28 17:55:40 +0000] [86] [INFO] Booting worker with pid: 86
[2025-04-28 17:58:16 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:82)
[2025-04-28 17:58:17 +0000] [82] [INFO] Worker exiting (pid: 82)
[2025-04-28 17:58:17 +0000] [39] [ERROR] Worker (pid:82) exited with code 1
[2025-04-28 17:58:17 +0000] [39] [ERROR] Worker (pid:82) exited with code 1.
[2025-04-28 17:58:17 +0000] [88] [INFO] Booting worker with pid: 88
[2025-04-29 09:06:20 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:78)
[2025-04-29 09:06:20 +0000] [78] [INFO] Worker exiting (pid: 78)
[2025-04-29 09:06:22 +0000] [39] [ERROR] Worker (pid:78) exited with code 1
[2025-04-29 09:06:22 +0000] [39] [ERROR] Worker (pid:78) exited with code 1.
[2025-04-29 09:06:22 +0000] [90] [INFO] Booting worker with pid: 90
[2025-04-29 09:10:31 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:84)
[2025-04-29 09:10:31 +0000] [84] [INFO] Worker exiting (pid: 84)
[2025-04-29 09:10:32 +0000] [39] [ERROR] Worker (pid:84) exited with code 1
[2025-04-29 09:10:32 +0000] [39] [ERROR] Worker (pid:84) exited with code 1.
[2025-04-29 09:10:32 +0000] [92] [INFO] Booting worker with pid: 92
[2025-04-29 12:31:39 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:88)
[2025-04-29 12:31:39 +0000] [88] [INFO] Worker exiting (pid: 88)
[2025-04-29 12:31:41 +0000] [39] [ERROR] Worker (pid:88) exited with code 1
[2025-04-29 12:31:41 +0000] [39] [ERROR] Worker (pid:88) exited with code 1.
[2025-04-29 12:31:41 +0000] [109] [INFO] Booting worker with pid: 109
[2025-04-29 12:46:13 +0000] [39] [CRITICAL] WORKER TIMEOUT (pid:86)
[2025-04-29 12:46:10 +0000] [86] [INFO] Worker exiting (pid: 86)
[2025-04-29 12:46:12 +0000] [39] [ERROR] Worker (pid:86) exited with code 1
[2025-04-29 12:46:12 +0000] [39] [ERROR] Worker (pid:86) exited with code 1.
[2025-04-29 12:46:12 +0000] [111] [INFO] Booting worker with pid: 111
[2025-04-29 14:36:31 +0100] [22570] [INFO] Starting gunicorn 23.0.0
[2025-04-29 14:36:31 +0100] [22570] [INFO] Listening at: http://0.0.0.0:9000 (22570)
[2025-04-29 14:36:31 +0100] [22570] [INFO] Using worker: sync
[2025-04-29 14:36:31 +0100] [22571] [INFO] Booting worker with pid: 22571
[2025-04-29 14:36:31 +0100] [22572] [INFO] Booting worker with pid: 22572
[2025-04-29 14:36:31 +0100] [22573] [INFO] Booting worker with pid: 22573
[2025-04-29 14:36:31 +0100] [22574] [INFO] Booting worker with pid: 22574
[2025-04-29 16:04:29 +0100] [22570] [INFO] Handling signal: int
[2025-04-29 16:04:29 +0100] [22573] [INFO] Worker exiting (pid: 22573)
[2025-04-29 16:04:29 +0100] [22571] [INFO] Worker exiting (pid: 22571)
[2025-04-29 16:04:29 +0100] [22574] [INFO] Worker exiting (pid: 22574)
[2025-04-29 16:04:29 +0100] [22572] [INFO] Worker exiting (pid: 22572)
[2025-04-29 16:04:29 +0100] [22570] [INFO] Shutting down: Master
[2025-04-29 17:50:03 +0100] [25099] [INFO] Starting gunicorn 23.0.0
[2025-04-29 17:50:03 +0100] [25099] [INFO] Listening at: http://0.0.0.0:9000 (25099)
[2025-04-29 17:50:03 +0100] [25099] [INFO] Using worker: sync
[2025-04-29 17:50:03 +0100] [25100] [INFO] Booting worker with pid: 25100
[2025-04-29 17:50:03 +0100] [25101] [INFO] Booting worker with pid: 25101
[2025-04-29 17:50:03 +0100] [25102] [INFO] Booting worker with pid: 25102
[2025-04-29 17:50:03 +0100] [25103] [INFO] Booting worker with pid: 25103
[2025-04-30 09:41:47 +0100] [25099] [INFO] Handling signal: int
[2025-04-30 09:41:47 +0100] [25100] [INFO] Worker exiting (pid: 25100)
[2025-04-30 09:41:47 +0100] [25103] [INFO] Worker exiting (pid: 25103)
[2025-04-30 09:41:47 +0100] [25102] [INFO] Worker exiting (pid: 25102)
[2025-04-30 09:41:47 +0100] [25101] [INFO] Worker exiting (pid: 25101)
[2025-04-30 09:41:47 +0100] [25099] [INFO] Shutting down: Master
[2025-04-30 09:52:45 +0100] [25921] [INFO] Starting gunicorn 23.0.0
[2025-04-30 09:52:45 +0100] [25921] [INFO] Listening at: http://0.0.0.0:9000 (25921)
[2025-04-30 09:52:45 +0100] [25921] [INFO] Using worker: sync
[2025-04-30 09:52:45 +0100] [25922] [INFO] Booting worker with pid: 25922
[2025-04-30 09:52:45 +0100] [25923] [INFO] Booting worker with pid: 25923
[2025-04-30 09:52:45 +0100] [25924] [INFO] Booting worker with pid: 25924
[2025-04-30 09:52:45 +0100] [25925] [INFO] Booting worker with pid: 25925
[2025-04-30 09:54:01 +0100] [25921] [INFO] Handling signal: int
[2025-04-30 09:54:01 +0100] [25922] [INFO] Worker exiting (pid: 25922)
[2025-04-30 09:54:01 +0100] [25924] [INFO] Worker exiting (pid: 25924)
[2025-04-30 09:54:01 +0100] [25923] [INFO] Worker exiting (pid: 25923)
[2025-04-30 09:54:01 +0100] [25925] [INFO] Worker exiting (pid: 25925)
[2025-04-30 09:54:01 +0100] [25921] [INFO] Shutting down: Master
[2025-04-30 09:56:14 +0100] [26012] [INFO] Starting gunicorn 23.0.0
[2025-04-30 09:56:14 +0100] [26012] [INFO] Listening at: http://0.0.0.0:9000 (26012)
[2025-04-30 09:56:14 +0100] [26012] [INFO] Using worker: sync
[2025-04-30 09:56:14 +0100] [26013] [INFO] Booting worker with pid: 26013
[2025-04-30 09:56:14 +0100] [26014] [INFO] Booting worker with pid: 26014
[2025-04-30 09:56:14 +0100] [26015] [INFO] Booting worker with pid: 26015
[2025-04-30 09:56:14 +0100] [26016] [INFO] Booting worker with pid: 26016
[2025-04-30 10:00:15 +0100] [26092] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:00:15 +0100] [26092] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:15 +0100] [26092] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:16 +0100] [26094] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:00:16 +0100] [26094] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:16 +0100] [26094] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:16 +0100] [26092] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:16 +0100] [26092] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:17 +0100] [26094] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:17 +0100] [26094] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:17 +0100] [26092] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:17 +0100] [26092] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:18 +0100] [26094] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:18 +0100] [26094] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:18 +0100] [26092] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:18 +0100] [26092] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:19 +0100] [26094] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:19 +0100] [26094] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:19 +0100] [26092] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:19 +0100] [26092] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:20 +0100] [26094] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:00:20 +0100] [26094] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:00:20 +0100] [26092] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:00:21 +0100] [26094] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:04:55 +0100] [26191] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:04:55 +0100] [26191] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:55 +0100] [26191] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:55 +0100] [26193] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:04:55 +0100] [26193] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:55 +0100] [26193] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:56 +0100] [26191] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:56 +0100] [26191] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:56 +0100] [26193] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:56 +0100] [26193] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:57 +0100] [26191] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:57 +0100] [26191] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:57 +0100] [26193] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:57 +0100] [26193] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:58 +0100] [26191] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:58 +0100] [26191] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:58 +0100] [26193] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:58 +0100] [26193] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:59 +0100] [26191] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:59 +0100] [26191] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:04:59 +0100] [26193] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:04:59 +0100] [26193] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:05:00 +0100] [26191] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:05:00 +0100] [26193] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:06:20 +0100] [26241] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:06:20 +0100] [26241] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:20 +0100] [26241] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:20 +0100] [26243] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:06:20 +0100] [26243] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:20 +0100] [26243] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:21 +0100] [26241] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:21 +0100] [26241] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:21 +0100] [26243] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:21 +0100] [26243] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:22 +0100] [26241] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:22 +0100] [26241] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:22 +0100] [26243] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:22 +0100] [26243] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:23 +0100] [26241] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:23 +0100] [26241] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:23 +0100] [26243] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:23 +0100] [26243] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:24 +0100] [26241] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:24 +0100] [26241] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:24 +0100] [26243] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:06:24 +0100] [26243] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:06:25 +0100] [26241] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:06:25 +0100] [26243] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:07:07 +0100] [26012] [INFO] Handling signal: term
[2025-04-30 10:07:07 +0100] [26013] [INFO] Worker exiting (pid: 26013)
[2025-04-30 10:07:07 +0100] [26014] [INFO] Worker exiting (pid: 26014)
[2025-04-30 10:07:07 +0100] [26016] [INFO] Worker exiting (pid: 26016)
[2025-04-30 10:07:07 +0100] [26015] [INFO] Worker exiting (pid: 26015)
[2025-04-30 10:07:07 +0100] [26012] [INFO] Shutting down: Master
[2025-04-30 10:14:20 +0100] [26424] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:14:20 +0100] [26424] [INFO] Listening at: http://0.0.0.0:9000 (26424)
[2025-04-30 10:14:20 +0100] [26424] [INFO] Using worker: sync
[2025-04-30 10:14:20 +0100] [26425] [INFO] Booting worker with pid: 26425
[2025-04-30 10:14:20 +0100] [26426] [INFO] Booting worker with pid: 26426
[2025-04-30 10:14:20 +0100] [26427] [INFO] Booting worker with pid: 26427
[2025-04-30 10:14:20 +0100] [26428] [INFO] Booting worker with pid: 26428
[2025-04-30 10:14:31 +0100] [26447] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:14:31 +0100] [26447] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:14:31 +0100] [26447] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:14:32 +0100] [26447] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:14:32 +0100] [26447] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:14:33 +0100] [26447] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:14:33 +0100] [26447] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:14:34 +0100] [26447] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:14:34 +0100] [26447] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:14:35 +0100] [26447] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:14:35 +0100] [26447] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:14:36 +0100] [26447] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:14:42 +0100] [26424] [INFO] Handling signal: int
[2025-04-30 10:14:42 +0100] [26426] [INFO] Worker exiting (pid: 26426)
[2025-04-30 10:14:42 +0100] [26428] [INFO] Worker exiting (pid: 26428)
[2025-04-30 10:14:42 +0100] [26427] [INFO] Worker exiting (pid: 26427)
[2025-04-30 10:14:42 +0100] [26425] [INFO] Worker exiting (pid: 26425)
[2025-04-30 10:14:42 +0100] [26424] [INFO] Shutting down: Master
[2025-04-30 10:14:57 +0100] [26463] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:14:57 +0100] [26463] [INFO] Listening at: http://0.0.0.0:9000 (26463)
[2025-04-30 10:14:57 +0100] [26463] [INFO] Using worker: sync
[2025-04-30 10:14:57 +0100] [26464] [INFO] Booting worker with pid: 26464
[2025-04-30 10:14:57 +0100] [26465] [INFO] Booting worker with pid: 26465
[2025-04-30 10:14:57 +0100] [26466] [INFO] Booting worker with pid: 26466
[2025-04-30 10:14:57 +0100] [26467] [INFO] Booting worker with pid: 26467
[2025-04-30 10:15:03 +0100] [26479] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:15:03 +0100] [26479] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:15:03 +0100] [26479] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:15:04 +0100] [26479] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:15:04 +0100] [26479] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:15:05 +0100] [26479] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:15:05 +0100] [26479] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:15:06 +0100] [26479] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:15:06 +0100] [26479] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:15:07 +0100] [26479] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2025-04-30 10:15:07 +0100] [26479] [ERROR] connection to ('0.0.0.0', 9000) failed: [Errno 48] Address already in use
[2025-04-30 10:15:08 +0100] [26479] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2025-04-30 10:18:22 +0100] [26463] [INFO] Handling signal: int
[2025-04-30 10:18:22 +0100] [26464] [INFO] Worker exiting (pid: 26464)
[2025-04-30 10:18:22 +0100] [26465] [INFO] Worker exiting (pid: 26465)
[2025-04-30 10:18:22 +0100] [26466] [INFO] Worker exiting (pid: 26466)
[2025-04-30 10:18:22 +0100] [26467] [INFO] Worker exiting (pid: 26467)
[2025-04-30 10:18:22 +0100] [26463] [INFO] Shutting down: Master
[2025-04-30 10:18:35 +0100] [26550] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:18:35 +0100] [26550] [INFO] Listening at: http://0.0.0.0:9000 (26550)
[2025-04-30 10:18:35 +0100] [26550] [INFO] Using worker: sync
[2025-04-30 10:18:35 +0100] [26553] [INFO] Booting worker with pid: 26553
[2025-04-30 10:18:35 +0100] [26554] [INFO] Booting worker with pid: 26554
[2025-04-30 10:18:35 +0100] [26555] [INFO] Booting worker with pid: 26555
[2025-04-30 10:18:35 +0100] [26556] [INFO] Booting worker with pid: 26556
[2025-04-30 10:19:36 +0100] [26550] [INFO] Handling signal: int
[2025-04-30 10:19:36 +0100] [26553] [INFO] Worker exiting (pid: 26553)
[2025-04-30 10:19:36 +0100] [26554] [INFO] Worker exiting (pid: 26554)
[2025-04-30 10:19:36 +0100] [26556] [INFO] Worker exiting (pid: 26556)
[2025-04-30 10:19:36 +0100] [26555] [INFO] Worker exiting (pid: 26555)
[2025-04-30 10:19:37 +0100] [26550] [INFO] Shutting down: Master
[2025-04-30 10:19:55 +0100] [26592] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:19:55 +0100] [26592] [INFO] Listening at: http://0.0.0.0:9000 (26592)
[2025-04-30 10:19:55 +0100] [26592] [INFO] Using worker: sync
[2025-04-30 10:19:55 +0100] [26595] [INFO] Booting worker with pid: 26595
[2025-04-30 10:19:55 +0100] [26596] [INFO] Booting worker with pid: 26596
[2025-04-30 10:19:55 +0100] [26597] [INFO] Booting worker with pid: 26597
[2025-04-30 10:19:55 +0100] [26598] [INFO] Booting worker with pid: 26598
[2025-04-30 10:23:28 +0100] [26592] [INFO] Handling signal: int
[2025-04-30 10:23:28 +0100] [26598] [INFO] Worker exiting (pid: 26598)
[2025-04-30 10:23:28 +0100] [26597] [INFO] Worker exiting (pid: 26597)
[2025-04-30 10:23:28 +0100] [26595] [INFO] Worker exiting (pid: 26595)
[2025-04-30 10:23:28 +0100] [26596] [INFO] Worker exiting (pid: 26596)
[2025-04-30 10:23:28 +0100] [26592] [INFO] Shutting down: Master
[2025-04-30 10:23:30 +0100] [26667] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:23:30 +0100] [26667] [INFO] Listening at: http://0.0.0.0:9000 (26667)
[2025-04-30 10:23:30 +0100] [26667] [INFO] Using worker: sync
[2025-04-30 10:23:30 +0100] [26669] [INFO] Booting worker with pid: 26669
[2025-04-30 10:23:30 +0100] [26671] [INFO] Booting worker with pid: 26671
[2025-04-30 10:23:30 +0100] [26672] [INFO] Booting worker with pid: 26672
[2025-04-30 10:23:30 +0100] [26673] [INFO] Booting worker with pid: 26673
[2025-04-30 10:26:45 +0100] [26667] [INFO] Handling signal: int
[2025-04-30 10:26:45 +0100] [26671] [INFO] Worker exiting (pid: 26671)
[2025-04-30 10:26:45 +0100] [26672] [INFO] Worker exiting (pid: 26672)
[2025-04-30 10:26:45 +0100] [26673] [INFO] Worker exiting (pid: 26673)
[2025-04-30 10:26:45 +0100] [26669] [INFO] Worker exiting (pid: 26669)
[2025-04-30 10:26:45 +0100] [26667] [INFO] Shutting down: Master
[2025-04-30 10:26:48 +0100] [26734] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:26:48 +0100] [26734] [INFO] Listening at: http://0.0.0.0:9000 (26734)
[2025-04-30 10:26:48 +0100] [26734] [INFO] Using worker: sync
[2025-04-30 10:26:48 +0100] [26736] [INFO] Booting worker with pid: 26736
[2025-04-30 10:26:48 +0100] [26738] [INFO] Booting worker with pid: 26738
[2025-04-30 10:26:48 +0100] [26739] [INFO] Booting worker with pid: 26739
[2025-04-30 10:26:48 +0100] [26740] [INFO] Booting worker with pid: 26740
[2025-04-30 10:32:33 +0100] [26734] [INFO] Handling signal: int
[2025-04-30 10:32:33 +0100] [26736] [INFO] Worker exiting (pid: 26736)
[2025-04-30 10:32:33 +0100] [26738] [INFO] Worker exiting (pid: 26738)
[2025-04-30 10:32:33 +0100] [26739] [INFO] Worker exiting (pid: 26739)
[2025-04-30 10:32:33 +0100] [26740] [INFO] Worker exiting (pid: 26740)
[2025-04-30 10:32:34 +0100] [26734] [INFO] Shutting down: Master
[2025-04-30 10:32:40 +0100] [26866] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:32:40 +0100] [26866] [INFO] Listening at: http://0.0.0.0:9000 (26866)
[2025-04-30 10:32:40 +0100] [26866] [INFO] Using worker: sync
[2025-04-30 10:32:40 +0100] [26868] [INFO] Booting worker with pid: 26868
[2025-04-30 10:32:40 +0100] [26870] [INFO] Booting worker with pid: 26870
[2025-04-30 10:32:40 +0100] [26871] [INFO] Booting worker with pid: 26871
[2025-04-30 10:32:40 +0100] [26872] [INFO] Booting worker with pid: 26872
[2025-04-30 10:36:06 +0100] [26866] [INFO] Handling signal: int
[2025-04-30 10:36:06 +0100] [26870] [INFO] Worker exiting (pid: 26870)
[2025-04-30 10:36:06 +0100] [26871] [INFO] Worker exiting (pid: 26871)
[2025-04-30 10:36:06 +0100] [26868] [INFO] Worker exiting (pid: 26868)
[2025-04-30 10:36:06 +0100] [26872] [INFO] Worker exiting (pid: 26872)
[2025-04-30 10:36:06 +0100] [26866] [INFO] Shutting down: Master
[2025-04-30 10:36:09 +0100] [26960] [INFO] Starting gunicorn 23.0.0
[2025-04-30 10:36:09 +0100] [26960] [INFO] Listening at: http://0.0.0.0:9000 (26960)
[2025-04-30 10:36:09 +0100] [26960] [INFO] Using worker: sync
[2025-04-30 10:36:09 +0100] [26962] [INFO] Booting worker with pid: 26962
[2025-04-30 10:36:09 +0100] [26964] [INFO] Booting worker with pid: 26964
[2025-04-30 10:36:09 +0100] [26965] [INFO] Booting worker with pid: 26965
[2025-04-30 10:36:09 +0100] [26966] [INFO] Booting worker with pid: 26966
[2025-04-30 11:08:27 +0100] [26960] [INFO] Handling signal: int
[2025-04-30 11:08:27 +0100] [26962] [INFO] Worker exiting (pid: 26962)
[2025-04-30 11:08:27 +0100] [26964] [INFO] Worker exiting (pid: 26964)
[2025-04-30 11:08:27 +0100] [26965] [INFO] Worker exiting (pid: 26965)
[2025-04-30 11:08:27 +0100] [26966] [INFO] Worker exiting (pid: 26966)
[2025-04-30 11:08:27 +0100] [26960] [INFO] Shutting down: Master
[2025-04-30 11:08:30 +0100] [27637] [INFO] Starting gunicorn 23.0.0
[2025-04-30 11:08:30 +0100] [27637] [INFO] Listening at: http://0.0.0.0:9000 (27637)
[2025-04-30 11:08:30 +0100] [27637] [INFO] Using worker: sync
[2025-04-30 11:08:30 +0100] [27639] [INFO] Booting worker with pid: 27639
[2025-04-30 11:08:30 +0100] [27640] [INFO] Booting worker with pid: 27640
[2025-04-30 11:08:30 +0100] [27642] [INFO] Booting worker with pid: 27642
[2025-04-30 11:08:30 +0100] [27643] [INFO] Booting worker with pid: 27643
[2025-04-30 11:15:23 +0100] [27637] [INFO] Handling signal: int
[2025-04-30 11:15:23 +0100] [27639] [INFO] Worker exiting (pid: 27639)
[2025-04-30 11:15:23 +0100] [27640] [INFO] Worker exiting (pid: 27640)
[2025-04-30 11:15:23 +0100] [27642] [INFO] Worker exiting (pid: 27642)
[2025-04-30 11:15:23 +0100] [27643] [INFO] Worker exiting (pid: 27643)
[2025-04-30 11:15:23 +0100] [27637] [INFO] Shutting down: Master
[2025-04-30 11:15:25 +0100] [27784] [INFO] Starting gunicorn 23.0.0
[2025-04-30 11:15:25 +0100] [27784] [INFO] Listening at: http://0.0.0.0:9000 (27784)
[2025-04-30 11:15:25 +0100] [27784] [INFO] Using worker: sync
[2025-04-30 11:15:25 +0100] [27786] [INFO] Booting worker with pid: 27786
[2025-04-30 11:15:25 +0100] [27787] [INFO] Booting worker with pid: 27787
[2025-04-30 11:15:25 +0100] [27789] [INFO] Booting worker with pid: 27789
[2025-04-30 11:15:25 +0100] [27790] [INFO] Booting worker with pid: 27790
[2025-04-30 11:43:33 +0100] [27784] [INFO] Handling signal: int
[2025-04-30 11:43:33 +0100] [27787] [INFO] Worker exiting (pid: 27787)
[2025-04-30 11:43:33 +0100] [27786] [INFO] Worker exiting (pid: 27786)
[2025-04-30 11:43:33 +0100] [27789] [INFO] Worker exiting (pid: 27789)
[2025-04-30 11:43:33 +0100] [27790] [INFO] Worker exiting (pid: 27790)
[2025-04-30 11:43:33 +0100] [27784] [INFO] Shutting down: Master
[2025-04-30 11:47:50 +0100] [28553] [INFO] Starting gunicorn 23.0.0
[2025-04-30 11:47:50 +0100] [28553] [INFO] Listening at: http://0.0.0.0:9000 (28553)
[2025-04-30 11:47:50 +0100] [28553] [INFO] Using worker: sync
[2025-04-30 11:47:50 +0100] [28555] [INFO] Booting worker with pid: 28555
[2025-04-30 11:47:50 +0100] [28556] [INFO] Booting worker with pid: 28556
[2025-04-30 11:47:50 +0100] [28558] [INFO] Booting worker with pid: 28558
[2025-04-30 11:47:50 +0100] [28559] [INFO] Booting worker with pid: 28559
[2025-04-30 11:48:54 +0100] [28553] [INFO] Handling signal: int
[2025-04-30 11:48:55 +0100] [28556] [INFO] Worker exiting (pid: 28556)
[2025-04-30 11:48:55 +0100] [28555] [INFO] Worker exiting (pid: 28555)
[2025-04-30 11:48:55 +0100] [28558] [INFO] Worker exiting (pid: 28558)
[2025-04-30 11:48:55 +0100] [28559] [INFO] Worker exiting (pid: 28559)
[2025-04-30 11:48:55 +0100] [28553] [INFO] Shutting down: Master
[2025-05-05 09:51:32 +0100] [11139] [INFO] Starting gunicorn 23.0.0
[2025-05-05 09:51:32 +0100] [11139] [INFO] Listening at: http://0.0.0.0:9000 (11139)
[2025-05-05 09:51:32 +0100] [11139] [INFO] Using worker: sync
[2025-05-05 09:51:32 +0100] [11142] [INFO] Booting worker with pid: 11142
[2025-05-05 09:51:32 +0100] [11143] [INFO] Booting worker with pid: 11143
[2025-05-05 09:51:32 +0100] [11144] [INFO] Booting worker with pid: 11144
[2025-05-05 09:51:32 +0100] [11145] [INFO] Booting worker with pid: 11145
